import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_fonts/google_fonts.dart';
import 'firebase_options.dart'; // Make sure this file exists (generated by FlutterFire)
import 'screens/login_screen.dart';
import 'screens/main_screen.dart';
import 'theme/colors.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MindFullApp());
}

class MindFullApp extends StatelessWidget {
  const MindFullApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MindFull',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        scaffoldBackgroundColor: AppColors.paperBackground, // From your Paper Theme
        primaryColor: AppColors.ink,
        textTheme: GoogleFonts.latoTextTheme(),
        useMaterial3: true,
      ),
      // Check if user is logged in
      home: StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }
          if (snapshot.hasData) {
            return const MainScreen(); // Go to the 4-Tab Shell
          }
          return const LoginScreen(); // Go to the Paper Login Screen
        },
      ),
    );
  }
}